#pragma once

#include <Geode/Geode.hpp>
#include "DecorationRules.hpp"

using namespace geode::prelude;

namespace AutoDecorator {

class Decorator {
public:
    Decorator();

    void setSettings(DecorationSettings const& settings);
    DecorationSettings const& getSettings() const;

    // Main entry point.
    void decorate(EditorUI* editor);

    // Remove objects generated by the decorator.
    void clear(EditorUI* editor);

private:
    DecorationSettings m_settings;

    void scanLevel(EditorUI* editor);

    void decorateStructure(
        EditorUI* editor,
        Structure const& structure
    );

    void createBlockDecoration(
        EditorUI* editor,
        Structure const& structure
    );

    void createSlopeDecoration(
        EditorUI* editor,
        Structure const& structure
    );

    void createGroundDecoration(
        EditorUI* editor,
        Structure const& structure
    );

    void createBackgroundDecoration(
        EditorUI* editor,
        Structure const& structure
    );
};

}
