#pragma once

#include <Geode/Geode.hpp>
#include "DecorationRules.hpp"

using namespace geode::prelude;

namespace AutoDecorator {

    class Decorator {
    public:

        Decorator();
        ~Decorator();

        // Start automatic decoration.
        void decorate(
            EditorUI* editor,
            DecorationSettings const& settings
        );

        // Remove decoration generated by this mod.
        void clearGeneratedDecoration(
            EditorUI* editor
        );

        // Change the selected theme.
        void setTheme(Theme theme);

        // Get the current settings.
        DecorationSettings const& getSettings() const;

    private:

        DecorationSettings m_settings;

        // Scan the current level.
        void scanLevel(
            EditorUI* editor
        );

        // Generate decoration around one structure.
        void decorateStructure(
            EditorUI* editor,
            Structure const& structure
        );

        // Create individual decoration types.
        void createBlockDecoration(
            EditorUI* editor,
            Structure const& structure
        );

        void createSlopeDecoration(
            EditorUI* editor,
            Structure const& structure
        );

        void createGroundDecoration(
            EditorUI* editor,
            Structure const& structure
        );

        void createBackgroundDecoration(
            EditorUI* editor,
            Structure const& structure
        );
    };

}
